name: Send mail

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: utility/reports  # Specify branch here

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/budgr-reports:latest

      - name: Run dist/index.js in Docker container
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/budgr-reports:latest node dist/index.js
